"""empty message

Revision ID: 151433c563a0
Revises: f7af5a6f1ee2
Create Date: 2025-12-21 14:53:22.940995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '151433c563a0'
down_revision: Union[str, Sequence[str], None] = 'f7af5a6f1ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_availability_employee_id_employee'), 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_availability_employee_id_employee'), type_='foreignkey')

    # ### end Alembic commands ###
